### ISSUE TITLE
Support for txt files

### ISSUE THREAD

**Issue by werunom** [kortina/vscode-markdown-notes#107]
**Is your feature request related to a problem? Please describe.**
Looks like the auto-fill for creating references to other notes works when all the notes are `md` files. However, in my vscode workspace, all notes are `txt` files. Hence, I cannot use the important feature of the extension --- auto-suggestions for creating references to other notes and see the backlinks.

**Describe the solution you'd like**
Can txt files be supported?

Thanks for this nice extension!

**Comment by digitalsignalperson** [comment]
I came here looking to see if it's possible to use wiki links in txt file. In a txt file if I have a wiki link, ctrl+click doesn't work. @werunom does it work for you? 

Would be cool to have a setting for "allowed extensions" or something. Would be cool to even have wiki links in source files or arbitrary other types of files.

**Comment by werunom** [comment]
@digitalsignalperson --- No! None of the features of the extension work for `txt` files. That is why I thought of raising this request.

**Comment by digitalsignalperson** [comment]
Ah got it! I wondered if I was missing something as it sounded like just auto-suggest wasn't working. So +1 for this feature :)

**Comment by thomaskoppelaar** [comment]
Hey @werunom @digitalsignalperson , 

I quickly looked into this issue, and it seems doable with a caveat.

First: The only code that would need to change is the `_rxFileExtension` pattern:
```js
static _rxFileExtensions = '\\.(md|markdown|mdx|fountain|txt)$'; // added the "|txt" here
```

The caveat for this to be fully implemented, is that you'd also have to tell VSCode to treat txt files as markdown: 
![image](https://user-images.githubusercontent.com/36331365/104643887-5f1d0380-56ad-11eb-81cf-33767ae9af5a.png)

From my very quick testing, this _should_ be everything that you have to do in order to make this work.

**Comment by werunom** [comment]
@thomaskoppelaar -- great to hear this! Would love to see this getting implemented.

**Comment by thomaskoppelaar** [comment]
Perhaps this pattern is something that could somehow be opened up as a configurable option - I might try to fiddle around with this once I have more time.
