### ISSUE TITLE
[Feature Request] Allow spaces in filename

### ISSUE THREAD

**Issue by lukakemperle** [kortina/vscode-markdown-notes#12]
Thank you for this amazing enhancement of VSCode: I can finally move away from Typora, The Archive or nvUltra.

Since my filenames include space, I'm facing problems clicking on the wiki-links.

```
Filename pattern: [[202002142107 Video editing]]
```

![20200423095043 Screenshot](https://user-images.githubusercontent.com/654580/80068868-0323b500-8549-11ea-9bee-8d00f97493e4.png)

1. Would be possible to ignore empty space in the filename and make clicking/navigating between notes possible?
2. Is it possible to escape creating dashes in the filename along with the note creation? As I said, all my notes contain the spaces in the filename...

**Comment by kortina** [comment]
There is another request to allow `_` in the filenames instead of `-` as the separator, which I def think we should add: https://github.com/kortina/vscode-markdown-notes/issues/17

But I am wondering how much the space characters in filenames would complicated the regexes. The main issue is that in order to get completion working properly, I had to modify `wordPattern` to include all of the valid filename characters we wanted to use (specifically I had to add `.` which is a little weird).

I think it would cause real weird side effects (probably break everything) if we had to add the space character to the `wordPattern` for markdown.

That said, if you can figure out how to get the completion working correctly with spaces in words, I would happily review a PR. I'm just not sure it is possible.

**Comment by kortina** [comment]
Clickable links will be addressed by #9. Update this title to request for allowing spaces in filename.

**Comment by kortina** [comment]
Closed by #29
