### ISSUE TITLE
Config option to use underscores instead of dashes as word separator (for new note creation)

### ISSUE THREAD

**Issue by jli** [kortina/vscode-markdown-notes#17]
I prefer using underscores to replace spaces in my filenames. I'd be great to have a config option for this.

Would be happy to send a PR if you think it's a reasonable idea!

**Comment by kortina** [comment]
Yes, something like `vscodeMarkdownNotes.newNoteReplacesSpacesWithCharacter`?

1. Make sure the default is `-`
2. I guess it should be an enum, with the only other option `_` for now, (1) because I can't really see another good option and (2) because we don't want to break this regex: https://github.com/kortina/vscode-markdown-notes/blob/dceb12a17397968eb30680bf67f26fceafc9c24d/src/extension.ts#L103

Happy to review a PR when you have one.

**Comment by kortina** [comment]
Closed by #29
