### ISSUE TITLE
Improve clarity of internal code

### ISSUE THREAD

**Issue by b3u** [kortina/vscode-markdown-notes#23]
I intentionally left the title vague. I found the code a bit difficult to comprehend at first. My code is probably no different.

**ideas**
- additional comments throughout
- put code in multiple files
- use a central `extension.ts`, and register everything there.

**Comment by b3u** [comment]
Question: Could this become a single boolean function?
https://github.com/kortina/vscode-markdown-notes/blob/472650fa219b07313df5c6ee188fb3136f7ec2cd/src/extension.ts#L25-L31

**Comment by kortina** [comment]
I'll cleanup the code / break into multiple files. Might also try to incorporate remark ast parser.

And yea, that could def be a single func but I just had some semantically useful variants. Maybe I will refactor, although I honestly wonder if anyone is going to use this thing in relative paths mode...

**Comment by b3u** [comment]
> although I honestly wonder if anyone is going to use this thing in relative paths mode

Guilty. :grinning:

**Comment by lukesmurray** [comment]
My experience integrating remark was that it makes accessing references etc much easier but it is way slower than regex searching and needs to be called async to avoid freezing the UI. So in summary it makes a more powerful extension but it increases the complexity of the code. 

I basically forked this code base a month ago and did a rewrite to create a remark AST for each document in the workspace. I store all of the remark ASTs in a redux store and when documents change I recreate the associated AST. 

This sounds convoluted but remark is an order of magnitude slower than regex searching so parsing all documents in the workspace at the moment you are seeking references for example is not a great user experience.

Once the ASTs are parsed I use reselect to get things like references, wikilinks, headings etc. This is basically instantaneous because I cache results per document.

I can share what I have with you but I'm happy to see a better solution or one that isn't tied to redux/reselect.

**Comment by b3u** [comment]
See https://github.com/kortina/vscode-markdown-notes/issues/13#issuecomment-629341359

@kortina I just rediscovered the extension. My first thought was that the codebase has become much larger. Do you want to reconsider splitting it up? Currently the extension has tags, backlinks *and* wikilinks. I'm worried that it will be hard to maintain everything in one extension. An extension pack would be just as easy to install, and would make it easier to add features like a map/graph view and zettelkasten support. Thoughts?
