### ISSUE TITLE
Enable Intellisense for normal Markdown links

### ISSUE THREAD

**Issue by morberg** [kortina/vscode-markdown-notes#32]
I use markdown links to my local files more often than wiki-links since I want different descriptive text based on context.

It would be useful to have intellisense suggestions available for markdown links (`[text](link)`) in addition to the `[[wiki-link]]` style. Perhaps it is already possible to achieve but my config is wrong?

I have tried pressing `^Space` after typing the first letter of the file I want to link to but it doesn't bring up any suggestions (I do get the "No suggestions" drop-down.)

My workspace settings are:
```json
{
    "editor.minimap.enabled": false,
    "explorer.sortOrder": "modified",
    "files.autoSave": "afterDelay",
    "[markdown]": {
        "editor.wordWrapColumn": 100,
        "editor.wordWrap": "wordWrapColumn",
        "editor.quickSuggestions": true,
        "editor.snippetSuggestions": "none",
        "editor.wordBasedSuggestions": false,
    },
}
```

**Comment by jn64** [comment]
1. For file suggestions in normal Markdown links, use [yzhang-gh/vscode-markdown](https://github.com/yzhang-gh/vscode-markdown) (it's a must-have for Markdown editing in VSCode)

2. It would be a bad idea for this extension to overload normal Markdown link syntax.

   A link like `[text](foo-bar)` becomes ambiguous. Is it a standard Markdown link to the file `foo-bar` in the same folder, or a wikilink to a file `foo-bar.md` potentially in a different folder?

3. If you want the features of wikilinks (whole point of using this extension), write the link separate from your descriptive text.

   Instead of writing this:

   ```
   [My hovercraft is full of eels.](hovercraft-eels.md)
   ```

   write this:

   ```
   My hovercraft is full of eels (see [[hovercraft-eels]]).
   ```

**Comment by kortina** [comment]
Agree w @jn64, don't think this should be part of this extension.
