### ISSUE TITLE
Slugs with apostrophes seem incorrect

### ISSUE THREAD

**Issue by bclinkinbeard** [kortina/vscode-markdown-notes#77]
**Describe the bug**

Creating a stub by Cmd clicking on a title that contains an apostrophe like "Let's", the file created uses `let-s`, which only works with a link syntax of [[Let s]]. The slug should be `lets`, which fixes/avoids the issue.

**To Reproduce**
- Create a wikilink to a non-existent note. [[Let's Go]]
- Command click on it
- See the filename is `let-s-go.md`

**Expected behavior**
The generated file should be named `lets-go.md`.

**Comment by kortina** [comment]
Hmm, ya, that is a little weird. I suppose we could special case apostrophe and just remove it (vs replacing with slug character as we do for all other special characters). We might want to make this a setting people can toggle, at least initially, because it will break things for people. Or write a little script to help people find files named this way.

Should be pretty easy to modify `slugifyTiitle` to do this tho:

https://github.com/kortina/vscode-markdown-notes/blob/13b2464983b64a51ee58832759b1b9ec11a48ed8/src/NoteWorkspace.ts#L264

**Comment by kortina** [comment]
NB: the Foam slugging behaviour is whatever GitHub Slugger does: https://github.com/Flet/github-slugger

TODO: look into how this works...

**Comment by kortina** [comment]
https://github.com/kortina/vscode-markdown-notes/pull/85 / v0.0.19 should resolve your issues if you switch to `vscodeMarkdownNotes.slugifyMethod` to "github-slugger"
